### ISSUE TITLE
Restore coverage checks of xqueue

### ISSUE THREAD

**Issue by timmc-edx** [openedx/xqueue#887]
xqueue has been using the deprecated codecov package, which finally was yanked from PyPI. In order to unblock CI, we've removed the broken coverage step (https://github.com/openedx/xqueue/pull/886) but this repo should have coverage restored at some point.

Most repos are using the https://github.com/codecov/codecov-action v3 action, but it's not immediately obvious how to get that to work with xqueue, which runs its tests in a docker container. (Do we need to copy a coverage.xml file out of the container? Or perhaps use a different approach entirely for getting MySQL in the testing environment?)

**Comment by jristau1984** [comment]
@spencertiberi can you transfer this to the Aurora backlog?

**Comment by spencertiberi** [comment]
Done!
