### ISSUE TITLE
[xqueue] Test Python 3.11 and 3.12

### ISSUE THREAD

**Issue by feanil** [openedx/xqueue#926]

**Comment by feanil** [comment]
Current XQueue Upgrade PR: https://github.com/openedx/xqueue/pull/923

**Comment by jfavellar90** [comment]
@feanil I created a new PR in https://github.com/openedx/xqueue/pull/932 to close this issue. It includes the feedback in #923 and some extra fixes. Could you please help me finding reviewers for it? I am paying close attention to the feedback on the PR.
